MAKE = make
CXX = g++
CXXFLAGS = -Wall
OPTFLAGS = -O3
DEBUG = -g
INCFLAGS = -I../lib 
LINKFLAGS = -L../lib -lpcasso
BINDIR = ../bin
ifeq ($(shell uname -o 2>/dev/null), Cygwin)
	LIBEXT=a
else
	LIBEXT=a
endif
